/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/check-username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Username */
        get: operations["check_username_v1_auth_check_username_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Return the full profile row for the authenticated user.
         */
        get: operations["get_me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert Profile */
        post: operations["upsert_profile_v1_auth_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/profile-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Status */
        get: operations["profile_status_v1_auth_profile_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Active Space */
        post: operations["set_active_space_v1_session_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Source */
        post: operations["capture_source_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Url */
        post: operations["create_upload_url_v1_sources_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthUser */
        AuthUser: {
            /** Email */
            email: string;
            /** Id */
            id: string;
        };
        /**
         * CaptureRequest
         * @description Payload the extension background worker POSTs to ``/v1/sources``.
         *
         *     ``content`` carries small text payloads (a YouTube transcript JSON string,
         *     an AI-chat thread JSON string, or an article's cleaned text). ``raw_html``
         *     is an optional companion for articles so the server can persist both
         *     ``raw/page.html`` and ``raw/extracted.txt`` (design §2.4 capture table).
         *     Large binary sources (PDF) do not use this endpoint — see
         *     ``/v1/sources/upload-url``.
         */
        CaptureRequest: {
            /** Anchor */
            anchor?: {
                [key: string]: unknown;
            } | null;
            /** Author */
            author?: string | null;
            /** Content */
            content?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /** Raw Html */
            raw_html?: string | null;
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
            /** Title */
            title: string;
            type: components["schemas"]["SourceType"];
            /** Url */
            url?: string | null;
        };
        /** CaptureResponse */
        CaptureResponse: {
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            user: components["schemas"]["AuthUser"];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** OnboardingStatusResponse */
        OnboardingStatusResponse: {
            /** Has Completed Onboarding */
            has_completed_onboarding: boolean;
        };
        /**
         * ProcessingStatus
         * @description Lifecycle of a source.
         *
         *     Phase 0 only ever emits ``queued`` (nothing processes it yet); the full
         *     set is declared here so the generated client contract is stable across
         *     phases.
         * @enum {string}
         */
        ProcessingStatus: "queued" | "fetching" | "chunking" | "embedding" | "summarizing" | "extracting" | "ready" | "failed";
        /**
         * ProfileUpsertRequest
         * @description Onboarding/profile write payload.
         */
        ProfileUpsertRequest: {
            /** Domain Of Focus */
            domain_of_focus: string;
            /** Full Name */
            full_name: string;
            /** Primary Role */
            primary_role: string;
            /** Referral Source */
            referral_source: string;
            /** Username */
            username: string;
        };
        /**
         * SessionResponse
         * @description Current user + the active learning space (may be null).
         */
        SessionResponse: {
            active_space?: components["schemas"]["Space"] | null;
            user: components["schemas"]["User"];
        };
        /** SetActiveSpaceRequest */
        SetActiveSpaceRequest: {
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
        };
        /**
         * SourceType
         * @description The kind of artifact being captured.
         * @enum {string}
         */
        SourceType: "youtube" | "article" | "ai_chat" | "pdf" | "note";
        /**
         * Space
         * @description A goal-scoped Learning Space.
         */
        Space: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * UploadUrlRequest
         * @description Request a pre-signed upload for a large binary source (PDF).
         */
        UploadUrlRequest: {
            /** Author */
            author?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /**
         * UploadUrlResponse
         * @description A tokenized Supabase upload URL the client PUTs the file to.
         *
         *     Note: this is NOT an S3 pre-signed PUT. The client PUTs the bytes to
         *     ``upload_url`` with header ``x-upsert: true``; ``token`` authorizes it.
         *     Single-use, short-lived.
         */
        UploadUrlResponse: {
            /** Path */
            path: string;
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Token */
            token: string;
            /** Upload Url */
            upload_url: string;
        };
        /**
         * User
         * @description The authenticated user (Phase 0: a fixed dev user).
         */
        User: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * UserLogin
         * @description Payload when a user signs in.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             * @example user@atlas-app.com
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UsernameAvailabilityResponse */
        UsernameAvailabilityResponse: {
            /** Is Taken */
            is_taken: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    check_username_v1_auth_check_username_get: {
        parameters: {
            query: {
                username: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsernameAvailabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_profile_v1_auth_profile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_status_v1_auth_profile_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    set_active_space_v1_session_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetActiveSpaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_source_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_url_v1_sources_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
