/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/check-username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Username */
        get: operations["check_username_v1_auth_check_username_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Return the full profile row for the authenticated user.
         */
        get: operations["get_me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert Profile */
        post: operations["upsert_profile_v1_auth_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/profile-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Status */
        get: operations["profile_status_v1_auth_profile_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Active Space */
        post: operations["set_active_space_v1_session_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Recent captures across every space — the dashboard's capture feed.
         */
        get: operations["list_sources_v1_sources_get"];
        put?: never;
        /** Capture Source */
        post: operations["capture_source_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Url */
        post: operations["create_upload_url_v1_sources_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/artifact-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact Url */
        get: operations["get_artifact_url_v1_sources__source_id__artifact_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_v1_sources__source_id__messages_get"];
        put?: never;
        /** Post Message */
        post: operations["post_message_v1_sources__source_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_v1_sources__source_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Spaces */
        get: operations["list_spaces_v1_spaces_get"];
        put?: never;
        /** Create Space */
        post: operations["create_space_v1_spaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{space_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Space Sources */
        get: operations["list_space_sources_v1_spaces__space_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactUrlResponse
         * @description A short-lived signed GET URL for one artifact in the private bucket.
         */
        ArtifactUrlResponse: {
            /** Expires In */
            expires_in: number;
            /** Url */
            url: string;
        };
        /** AuthUser */
        AuthUser: {
            /** Email */
            email: string;
            /** Id */
            id: string;
        };
        /**
         * CaptureRequest
         * @description Payload the extension background worker POSTs to ``/v1/sources``.
         *
         *     ``content`` carries small text payloads (a YouTube transcript JSON string,
         *     an AI-chat thread JSON string, or an article's cleaned text). ``raw_html``
         *     is an optional companion for articles so the server can persist both
         *     ``raw/page.html`` and ``raw/extracted.txt`` (design §2.4 capture table).
         *     Large binary sources (PDF) do not use this endpoint — see
         *     ``/v1/sources/upload-url``.
         */
        CaptureRequest: {
            /** Anchor */
            anchor?: {
                [key: string]: unknown;
            } | null;
            /** Author */
            author?: string | null;
            /** Content */
            content?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /** Raw Html */
            raw_html?: string | null;
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
            /** Title */
            title: string;
            type: components["schemas"]["SourceType"];
            /** Url */
            url?: string | null;
        };
        /** CaptureResponse */
        CaptureResponse: {
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /**
         * CreateSpaceRequest
         * @description Payload for creating a Learning Space, e.g. ``{"name": "Claude Code"}``.
         */
        CreateSpaceRequest: {
            /** Goal Text */
            goal_text?: string | null;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            user: components["schemas"]["AuthUser"];
        };
        /** MessageListResponse */
        MessageListResponse: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** OnboardingStatusResponse */
        OnboardingStatusResponse: {
            /** Has Completed Onboarding */
            has_completed_onboarding: boolean;
        };
        /**
         * ProcessingStatus
         * @description Lifecycle of a source.
         *
         *     Phase 0 only ever emits ``queued`` (nothing processes it yet); the full
         *     set is declared here so the generated client contract is stable across
         *     phases.
         * @enum {string}
         */
        ProcessingStatus: "queued" | "fetching" | "chunking" | "embedding" | "summarizing" | "extracting" | "ready" | "failed";
        /**
         * ProfileUpsertRequest
         * @description Onboarding/profile write payload.
         */
        ProfileUpsertRequest: {
            /** Domain Of Focus */
            domain_of_focus: string;
            /** Full Name */
            full_name: string;
            /** Primary Role */
            primary_role: string;
            /** Referral Source */
            referral_source: string;
            /** Username */
            username: string;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Content */
            content: string;
        };
        /** SendMessageResponse */
        SendMessageResponse: {
            assistant_message: components["schemas"]["ChatMessage"];
            user_message: components["schemas"]["ChatMessage"];
        };
        /**
         * SessionResponse
         * @description Current user + the active learning space (may be null).
         */
        SessionResponse: {
            active_space?: components["schemas"]["Space"] | null;
            user: components["schemas"]["User"];
        };
        /** SetActiveSpaceRequest */
        SetActiveSpaceRequest: {
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
        };
        /**
         * SourceCounts
         * @description Per-type capture counts for a space, as returned by the counts RPC.
         */
        SourceCounts: {
            /**
             * Ai Chat
             * @default 0
             */
            ai_chat: number;
            /**
             * Article
             * @default 0
             */
            article: number;
            /**
             * Note
             * @default 0
             */
            note: number;
            /**
             * Pdf
             * @default 0
             */
            pdf: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Youtube
             * @default 0
             */
            youtube: number;
        };
        /** SourceListResponse */
        SourceListResponse: {
            /** Sources */
            sources: components["schemas"]["SourceSummary"][];
        };
        /**
         * SourceSummary
         * @description A captured source. ``storage_prefix`` is deliberately not exposed —
         *     artifacts are reached through ``GET /v1/sources/{id}/artifact-url``.
         */
        SourceSummary: {
            /** Author */
            author?: string | null;
            /** Captured At */
            captured_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
            /** Space Name */
            space_name?: string | null;
            /** Title */
            title: string;
            type: components["schemas"]["SourceType"];
            /** Url */
            url?: string | null;
        };
        /**
         * SourceType
         * @description The kind of artifact being captured.
         * @enum {string}
         */
        SourceType: "youtube" | "article" | "ai_chat" | "pdf" | "note";
        /**
         * Space
         * @description A goal-scoped Learning Space (the identity slice embedded in a session).
         */
        Space: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /** SpaceListResponse */
        SpaceListResponse: {
            /** Spaces */
            spaces: components["schemas"]["SpaceSummary"][];
        };
        /**
         * SpaceSummary
         * @description A space plus enough aggregate detail to render a dashboard tile.
         */
        SpaceSummary: {
            /** Created At */
            created_at?: string | null;
            /** Goal Text */
            goal_text?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Captured At */
            last_captured_at?: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * @default {
             *       "ai_chat": 0,
             *       "article": 0,
             *       "note": 0,
             *       "pdf": 0,
             *       "total": 0,
             *       "youtube": 0
             *     }
             */
            source_counts: components["schemas"]["SourceCounts"];
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Generated */
            generated: boolean;
            /** Model */
            model: string | null;
            /** Summarized At */
            summarized_at: string | null;
            /** Summary */
            summary: string;
        };
        /**
         * UploadUrlRequest
         * @description Request a pre-signed upload for a large binary source (PDF).
         */
        UploadUrlRequest: {
            /** Author */
            author?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /**
         * UploadUrlResponse
         * @description A tokenized Supabase upload URL the client PUTs the file to.
         *
         *     Note: this is NOT an S3 pre-signed PUT. The client PUTs the bytes to
         *     ``upload_url`` with header ``x-upsert: true``; ``token`` authorizes it.
         *     Single-use, short-lived.
         */
        UploadUrlResponse: {
            /** Path */
            path: string;
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Token */
            token: string;
            /** Upload Url */
            upload_url: string;
        };
        /**
         * User
         * @description The authenticated user.
         */
        User: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * UserLogin
         * @description Payload when a user signs in.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             * @example user@atlas-app.com
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UsernameAvailabilityResponse */
        UsernameAvailabilityResponse: {
            /** Is Taken */
            is_taken: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    check_username_v1_auth_check_username_get: {
        parameters: {
            query: {
                username: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsernameAvailabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_profile_v1_auth_profile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_status_v1_auth_profile_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_v1_session_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_active_space_v1_session_active_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetActiveSpaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_v1_sources_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_source_v1_sources_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_url_v1_sources_upload_url_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_url_v1_sources__source_id__artifact_url_get: {
        parameters: {
            query?: {
                key?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_v1_sources__source_id__messages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_v1_sources__source_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_v1_sources__source_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spaces_v1_spaces_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_space_v1_spaces_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_space_sources_v1_spaces__space_id__sources_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
